// Comprehensive list of 400+ popular Google Fonts
// Organized by category for better UX and font discovery
export const GOOGLE_FONTS = [
  // === SANS SERIF - Most Popular & Versatile ===
  "Inter",
  "Roboto",
  "Open Sans",
  "Lato",
  "Montserrat",
  "Poppins",
  "Source Sans Pro",
  "Oswald",
  "Raleway",
  "PT Sans",
  "Nunito",
  "Ubuntu",
  "Work Sans",
  "Fira Sans",
  "Barlow",
  "DM Sans",
  "Manrope",
  "Space Grotesk",
  "Plus Jakarta Sans",
  "Mulish",
  "Red Hat Display",
  "Outfit",
  "Lexend",
  "Sora",
  "Urbanist",
  "Be Vietnam Pro",
  "Epilogue",
  "Public Sans",
  "IBM Plex Sans",
  "Noto Sans",
  "Rubik",
  "Karla",
  "Hind",
  "Cabin",
  "Oxygen",
  "Exo",
  "Questrial",
  "Pontano Sans",
  "ABeeZee",
  "Asap",
  "Gudea",
  "Hammersmith One",
  "Varela Round",
  "Dosis",
  "Catamaran",
  "Muli",
  "Quicksand",
  "Comfortaa",
  "Assistant",
  "Heebo",
  "Overpass",
  "Titillium Web",
  "Libre Franklin",
  "Chivo",
  "Saira",
  "Mukti",
  "Encode Sans",
  "Jost",
  "Commissioner",
  "Figtree",
  "Schibsted Grotesk",
  "Onest",
  "Geist",
  
  // === SERIF - Elegant & Traditional ===
  "Playfair Display",
  "Merriweather",
  "Libre Baskerville",
  "Crimson Text",
  "Cormorant Garamond",
  "EB Garamond",
  "Vollkorn",
  "Alegreya",
  "Cardo",
  "Gentium Plus",
  "Neuton",
  "Old Standard TT",
  "Bitter",
  "Arvo",
  "Rokkitt",
  "Crete Round",
  "Quando",
  "Adamina",
  "Copse",
  "Kameron",
  "Lora",
  "PT Serif",
  "Crimson Pro",
  "Source Serif Pro",
  "IBM Plex Serif",
  "Spectral",
  "Zilla Slab",
  "Slabo 27px",
  "Slabo 13px",
  "Domine",
  "Noticia Text",
  "Tinos",
  "Gelasio",
  "Frank Ruhl Libre",
  "Cormorant",
  "Faustina",
  "Literata",
  "Petrona",
  "Newsreader",
  "Fraunces",
  "Brygada 1918",
  "Bodoni Moda",
  "DM Serif Display",
  "DM Serif Text",
  "Libre Caslon Text",
  "Libre Caslon Display",
  "Yeseva One",
  "Ultra",
  "Abril Fatface",
  "Coustard",
  "Enriqueta",
  "Judson",
  "Mate",
  "Mate SC",
  "Radley",
  "Volkhov",
  
  // === DISPLAY & DECORATIVE - Bold & Eye-catching ===
  "Bebas Neue",
  "Anton",
  "Righteous",
  "Fredoka One",
  "Pacifico",
  "Lobster",
  "Amatic SC",
  "Archivo Black",
  "Bangers",
  "Bungee",
  "Creepster",
  "Orbitron",
  "Russo One",
  "Staatliches",
  "Teko",
  "Titan One",
  "Yellowtail",
  "Fjalla One",
  "Francois One",
  "Squada One",
  "Alfa Slab One",
  "Black Ops One",
  "Passion One",
  "Wallpoet",
  "Monoton",
  "Bungee Shade",
  "Bungee Outline",
  "Bungee Inline",
  "Bungee Hairline",
  "Fredoka",
  "Bowlby One",
  "Bowlby One SC",
  "Kalam",
  "Chewy",
  "Bubblegum Sans",
  "Modak",
  "Shrikhand",
  "Bree Serif",
  "Patua One",
  "Coda",
  "Fugaz One",
  "Righteous",
  "Sigmar One",
  "Lilita One",
  "Fredericka the Great",
  "Griffy",
  "Creepster",
  "Eater",
  "Nosifer",
  "Butcherman",
  "Chonburi",
  "Fascinate",
  "Fascinate Inline",
  "Jolly Lodger",
  "Metal Mania",
  "Rye",
  "Smokum",
  "Special Elite",
  "Stalinist One",
  "Vampiro One",
  
  // === SCRIPT & HANDWRITING - Elegant & Personal ===
  "Dancing Script",
  "Great Vibes",
  "Satisfy",
  "Kaushan Script",
  "Caveat",
  "Allura",
  "Alex Brush",
  "Arizonia",
  "Bad Script",
  "Berkshire Swash",
  "Bilbo",
  "Calligraffitti",
  "Cookie",
  "Courgette",
  "Damion",
  "Delius",
  "Euphoria Script",
  "Handlee",
  "Indie Flower",
  "Leckerli One",
  "Marck Script",
  "Patrick Hand",
  "Permanent Marker",
  "Reenie Beanie",
  "Rock Salt",
  "Shadows Into Light",
  "Sue Ellen Francisco",
  "Architects Daughter",
  "Kalam",
  "Caveat Brush",
  "Homemade Apple",
  "Just Me Again Down Here",
  "Kristi",
  "La Belle Aurore",
  "League Script",
  "Loved by the King",
  "Markerfield",
  "Nothing You Could Do",
  "Over the Rainbow",
  "Schoolbell",
  "Short Stack",
  "Waiting for the Sunrise",
  "Walter Turncoat",
  "Zeyada",
  "Amatic SC",
  "Annie Use Your Telescope",
  "Coming Soon",
  "Crafty Girls",
  "Gloria Hallelujah",
  "Gochi Hand",
  "Covered By Your Grace",
  "Kimberly",
  "Neucha",
  "Pangolin",
  "Sriracha",
  "Sunshiney",
  "The Girl Next Door",
  
  // === MONOSPACE - Code & Technical ===
  "JetBrains Mono",
  "Fira Code",
  "Source Code Pro",
  "Roboto Mono",
  "Space Mono",
  "IBM Plex Mono",
  "Inconsolata",
  "Ubuntu Mono",
  "Courier Prime",
  "Anonymous Pro",
  "PT Mono",
  "Overpass Mono",
  "Cutive Mono",
  "Nova Mono",
  "VT323",
  "Share Tech Mono",
  "Oxygen Mono",
  "Cousine",
  "Droid Sans Mono",
  "Noto Sans Mono",
  "Red Hat Mono",
  "Azeret Mono",
  "B612 Mono",
  "Cascadia Code",
  "Commit Mono",
  "Fira Mono",
  "Fragment Mono",
  "Geist Mono",
  "Major Mono Display",
  "Martian Mono",
  "Nanum Gothic Coding",
  "Roboto Slab",
  "Spline Sans Mono",
  "Syne Mono",
  "Xanh Mono",
  
  // === CONDENSED & NARROW - Space-efficient ===
  "Oswald",
  "Fjalla One",
  "Yanone Kaffeesatz",
  "Pathway Gothic One",
  "Arimo",
  "Abel",
  "Economica",
  "Cuprum",
  "Armata",
  "Candal",
  "Carme",
  "Duru Sans",
  "Electrolize",
  "Exo 2",
  "Geo",
  "Jura",
  "Michroma",
  "Orbitron",
  "Quantico",
  "Rationale",
  "Ruda",
  "Strait",
  "Syncopate",
  "Telex",
  "Unica One",
  
  // === ROUNDED & FRIENDLY - Approachable ===
  "Nunito",
  "Comfortaa",
  "Quicksand",
  "Varela Round",
  "Rubik",
  "Poppins",
  "Nunito Sans",
  "Fredoka",
  "Lexend",
  "Readex Pro",
  "M PLUS Rounded 1c",
  "Baloo 2",
  "Balsamiq Sans",
  "Bai Jamjuree",
  "Chakra Petch",
  "Changa",
  "Comfortaa",
  "Concert One",
  "Dosis",
  "Hammersmith One",
  "Hind Siliguri",
  "Itim",
  "Kanit",
  "Kosugi Maru",
  "Livvic",
  "Mitr",
  "Niramit",
  "Nunito",
  "Prompt",
  "Sarabun",
  "Taviraj",
  "Truculenta",
  "Varela",
  "Viga",
  
  // === GEOMETRIC & MODERN - Clean & Minimal ===
  "Montserrat",
  "Raleway",
  "Lato",
  "Work Sans",
  "Barlow",
  "DM Sans",
  "Manrope",
  "Space Grotesk",
  "Plus Jakarta Sans",
  "Inter",
  "Outfit",
  "Sora",
  "Urbanist",
  "Be Vietnam Pro",
  "Epilogue",
  "Public Sans",
  "Red Hat Display",
  "Figtree",
  "Schibsted Grotesk",
  "Onest",
  "Geist",
  "Albert Sans",
  "Anybody",
  "Archivo",
  "Atkinson Hyperlegible",
  "Bricolage Grotesque",
  "Cabinet Grotesk",
  "Familjen Grotesk",
  "General Sans",
  "Golos Text",
  "Instrument Sans",
  "Kumbh Sans",
  "League Spartan",
  "Manrope",
  "Martian Grotesk",
  "Noto Sans Display",
  "Onest",
  "Outfit",
  "Plus Jakarta Sans",
  "Satoshi",
  "Schibsted Grotesk",
  "Space Grotesk",
  "Switzer",
  "Synonym",
  "Untitled Sans",
  "Work Sans",
  
  // === VINTAGE & RETRO - Classic Appeal ===
  "Playfair Display",
  "Crimson Text",
  "Old Standard TT",
  "Vollkorn",
  "Alegreya",
  "Cardo",
  "Gentium Plus",
  "EB Garamond",
  "Cormorant Garamond",
  "Libre Baskerville",
  "Neuton",
  "Bitter",
  "Arvo",
  "Rokkitt",
  "Crete Round",
  "Quando",
  "Adamina",
  "Copse",
  "Kameron",
  "Abril Fatface",
  "Alfa Slab One",
  "Bevan",
  "Bree Serif",
  "Cabin Sketch",
  "Chela One",
  "Fredericka the Great",
  "Griffy",
  "Henny Penny",
  "Irish Grover",
  "Jim Nightshade",
  "Kenia",
  "Lobster Two",
  "Love Ya Like A Sister",
  "Luckiest Guy",
  "Maiden Orange",
  "Meddon",
  "Mountains of Christmas",
  "Mystery Quest",
  "New Rocker",
  "Nosifer",
  "Pirata One",
  "Rammetto One",
  "Rye",
  "Sancreek",
  "Sevillana",
  "Smokum",
  "Special Elite",
  "Stalinist One",
  "Trade Winds",
  "Uncial Antiqua",
  "UnifrakturCook",
  "UnifrakturMaguntia",
  "Vampiro One",
  "Vast Shadow",
  "Vintage",
]

// Enhanced font categories with more fonts per category
export const FONT_CATEGORIES = {
  "Most Popular": [
    "Inter", "Roboto", "Open Sans", "Lato", "Montserrat", "Poppins", 
    "Source Sans Pro", "Oswald", "Raleway", "PT Sans", "Nunito", "Ubuntu",
    "Work Sans", "Fira Sans", "Playfair Display", "Merriweather"
  ],
  "Sans Serif": [
    "Inter", "Roboto", "Open Sans", "Lato", "Montserrat", "Poppins",
    "Work Sans", "DM Sans", "Manrope", "Space Grotesk", "Plus Jakarta Sans",
    "Outfit", "Lexend", "Sora", "Urbanist", "Be Vietnam Pro"
  ],
  "Serif": [
    "Playfair Display", "Merriweather", "Libre Baskerville", "Crimson Text", 
    "EB Garamond", "Lora", "Vollkorn", "Alegreya", "Bitter", "Arvo",
    "PT Serif", "Crimson Pro", "Source Serif Pro", "IBM Plex Serif", "Spectral"
  ],
  "Display": [
    "Bebas Neue", "Anton", "Righteous", "Fredoka One", "Pacifico", 
    "Lobster", "Amatic SC", "Comfortaa", "Russo One", "Bangers",
    "Bungee", "Archivo Black", "Staatliches", "Teko", "Titan One"
  ],
  "Script": [
    "Dancing Script", "Great Vibes", "Satisfy", "Kaushan Script", 
    "Caveat", "Allura", "Alex Brush", "Cookie", "Handlee", "Indie Flower",
    "Permanent Marker", "Shadows Into Light", "Architects Daughter", "Reenie Beanie"
  ],
  "Monospace": [
    "JetBrains Mono", "Fira Code", "Source Code Pro", "Roboto Mono", 
    "Space Mono", "IBM Plex Mono", "Inconsolata", "Ubuntu Mono",
    "Courier Prime", "Anonymous Pro", "PT Mono", "Overpass Mono"
  ],
  "Rounded": [
    "Nunito", "Comfortaa", "Quicksand", "Varela Round", "Rubik",
    "Fredoka", "Lexend", "Baloo 2", "Concert One", "Dosis",
    "Kanit", "Mitr", "Prompt", "Viga"
  ],
  "Condensed": [
    "Oswald", "Fjalla One", "Yanone Kaffeesatz", "Pathway Gothic One",
    "Abel", "Economica", "Cuprum", "Armata", "Electrolize", "Jura"
  ],
  "Vintage": [
    "Abril Fatface", "Alfa Slab One", "Bevan", "Bree Serif", "Fredericka the Great",
    "Griffy", "Old Standard TT", "Special Elite", "Rye", "Uncial Antiqua"
  ]
}

// Check if a font is a Google Font
export function isGoogleFont(fontName: string): boolean {
  return GOOGLE_FONTS.includes(fontName)
}

// Get font category
export function getFontCategory(fontName: string): string | null {
  for (const [category, fonts] of Object.entries(FONT_CATEGORIES)) {
    if (fonts.includes(fontName)) {
      return category
    }
  }
  return null
}

// Get fonts by category
export function getFontsByCategory(category: string): string[] {
  return FONT_CATEGORIES[category as keyof typeof FONT_CATEGORIES] || []
}

// Get all available categories
export function getAllCategories(): string[] {
  return Object.keys(FONT_CATEGORIES)
}

// Search fonts by name
export function searchFonts(query: string): string[] {
  const lowerQuery = query.toLowerCase()
  return GOOGLE_FONTS.filter(font => 
    font.toLowerCase().includes(lowerQuery)
  )
}

// Get random fonts from a category
export function getRandomFontsFromCategory(category: string, count: number = 5): string[] {
  const categoryFonts = getFontsByCategory(category)
  const shuffled = [...categoryFonts].sort(() => Math.random() - 0.5)
  return shuffled.slice(0, count)
}

// Get font statistics
export function getFontStats() {
  return {
    total: GOOGLE_FONTS.length,
    categories: Object.keys(FONT_CATEGORIES).length,
    byCategory: Object.fromEntries(
      Object.entries(FONT_CATEGORIES).map(([cat, fonts]) => [cat, fonts.length])
    )
  }
}
